### ISSUE TITLE
Inquirer type confirm doesn't work

### ISSUE THREAD

**Issue by bialesdaniel** [ewnd9/inquirer-test#1]
I am trying to use this to respond to 
```
{
    name: "push",
    message: "Would you like to push to your repo?",
    type: "confirm"
}
```
I cannot seen to pass 'Y' to that question

I'm doing 
```
await (run (await callMethod(),['Y',ENTER]))

**Comment by ewnd9** [comment]
The first argument of `run` should be a path to a Node.js script.

See the example from README:

```js
const cliPath = __dirname + '/cli.js';

test('press enter', async t => {
  const result = await(run(cliPath, [ENTER]));
...
```

**Comment by dsc03** [comment]
Does this mean that each file must have one inquirer prompt associated with it? What if we want to separately test multiple functions in the same file?

**Comment by ewnd9** [comment]
Just create a wrapper like:

```js
const handlers = require('./handlers')
handlers[process.argv[2]]()
```

**Comment by kristianmandrup** [comment]
Please improve the example in the documentation. Not clear what is being tested.
You have a prompt handler which outputs to console. I imagine you test on the result passed to the function, not the output to the console!?
Cheers.

**Comment by ewnd9** [comment]
Closing for now, feel free to reopen if conversations in #2 and #3 don't clear things up
