### ISSUE TITLE
Improve docs - how to test generator

### ISSUE THREAD

**Issue by kristianmandrup** [ewnd9/inquirer-test#2]
Please improve docs. Not sure what is being tested from reading the docs, but I assume it is the answer resulting from the first prompt (after `filter` and `validation` etc. ?)

How can I use this to test a CLI generator such as [plop](https://github.com/amwmedia/plop)?

A plop generator is typically run using `plop [generator name]`, then proceeds through a number of prompts using inquirer, similar to Yeoman.

**Comment by kristianmandrup** [comment]
Looking into the code, it looks pretty hardcoded? would be nice with more flexibility built in, such as providing custom proc factory method or sth

```js
var proc = spawn('node', [cliPath], { stdio: [null, null, null] });
```

**Comment by ewnd9** [comment]
> Please improve docs. Not sure what is being tested from reading the docs, but I assume it is the answer resulting from the first prompt (after filter and validation etc. ?)

You can test output of commands with regex or side effects from running a script. E.g. with `plop` you provide a combinations of control keys and text inputs and ensure that files are generated with `fs` or other modules.

> would be nice with more flexibility built in, such as providing custom proc factory method or sth

I can think only of providing a way to pass full arguments array

```js
module.exports = function(args, combo, timeout) {
  if (!timeout) {
    timeout = 200;
  }
  
  var proc = spawn('node', args, { stdio: [null, null, null] });
  ...
}

import test from 'ava';
import run, { UP, DOWN, ENTER } from 'inquirer-test';

const cliPath = __dirname + '/cli.js';

test('press enter', async t => {
  const result = await(run([cliPath, '--custom-arg'], [ENTER]));
  t.regex(result, new RegExp('TEST-1', 'g'));
});
```

Would it be sufficient?

**Comment by kristianmandrup** [comment]
Thanks. Would be nice to put this in a recipe document, docs folder or the Readme or wiki
